apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-counter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-counter-app
  template:
    metadata:
      labels:
        app: demo-counter-app
    spec:
      containers:
      - name: demo-counter-app
        image: viswar4/demo-counter-app:v1.49
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9099
